[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 20_000
evm_version = "paris"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
quote_style = "double"
